version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: apple
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: challenge1
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://apple:yourpassword@db:5432/challenge1
      PORT: 3000

